
IGNORE_TAGS            = ["style", "script"]
QP_ROOT    = {'Computers': ['cpu',
                        'java',
                        'module',
                        'multimedia',
                        'perl',
                        'vb',
                        'agp card',
                        'application windows',
                        'applet code',
                        'array code',
                        'audio file',
                        'avi file',
                        'bios',
                        'buffer code',
                        'bytes code',
                        'shareware',
                        'card drivers',
                        'card graphics',
                        'card pc',
                        'pc windows'],
                        'Health': ['acupuncture',
                        'aerobic',
                        'aerobics',
                        'aids',
                        'cancer',
                        'cardiology',
                        'cholesterol',
                        'diabetes',
                        'diet',
                        'fitness',
                        'hiv',
                        'insulin',
                        'nurse',
                        'squats',
                        'treadmill',
                        'walkers',
                        'calories fat',
                        'carb carbs',
                        'doctor health',
                        'doctor medical',
                        'eating fat',
                        'fat muscle',
                        'health medicine',
                        'health nutritional',
                        'hospital medical',
                        'hospital patients',
                        'medical patient',
                        'medical treatment',
                        'patients treatment'],
                        'Sports':
                        ['laker',
                        'ncaa',
                        'pacers',
                        'soccer',
                        'teams',
                        'wnba',
                        'nba',
                        'avg league',
                        'avg nba',
                        'ball league',
                        'ball referee',
                        'ball team',
                        'blazers game',
                        'championship team',
                        'club league',
                        'fans football',
                        'game league']}
        
QP_COMPUTERS = {'Hardware': ['bios',
                'motherboard', 
                'board fsb', 
                'board overclocking', 
                'fsb overclocking', 
                'bios controller ide', 
                'cables drive floppy',
                'cpu',
                'cache',
                'solid state drive',
                'RAID',
                'multicore',
                'Intel'], 
                'Programming': ['actionlistener', 
                'algorithms', 
                'alias', 
                'alloc', 
                'ansi', 
                'api', 
                'applet', 
                'argument', 
                'array', 
                'binary', 
                'boolean', 
                'borland', 
                'char', 
                'class', 
                'code', 
                'compile', 
                'compiler', 
                'component', 
                'container', 
                'controls', 
                'cpan', 
                'java', 
                'perl']}
                
                
QP_HEALTH = {'Diseases': ['aids', 
                'cancer', 
                'dental', 
                'diabetes', 
                'hiv', 
                'cardiology', 
                'aspirin cardiologist', 
                'aspirin cholesterol', 
                'blood heart', 
                'blood insulin', 
                'cholesterol doctor', 
                'cholesterol lipitor', 
                'heart surgery', 
                'radiation treatment'],
                'Fitness': 
                ['aerobic', 
                'fat', 
                'fitness', 
                'walking', 
                'workout', 
                'acid diets', 
                'bodybuilding protein', 
                'calories protein', 
                'calories weight', 
                'challenge walk', 
                'dairy milk', 
                'eating protein', 
                'eating weight', 
                'exercise protein', 
                'exercise weight'] }
                
QP_SPORTS = {'Soccer': ['uefa',
                'leeds',
                'bayern',
                'bundesliga',
                'premiership',
                'lazio',
                'mls',
                'hooliganism',
                'juventus',
                'liverpool',
                'fifa'],
                'Basketball': 
                ['nba',
                'pacers',
                'kobe',
                'laker',
                'shaq', 
                'blazers',
                'knicks',
                'sabonis',
                'shaquille',
                'laettner',
                'wnba',
                'rebounds',
                'dunks']}